 name: .NET Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Packages
        run: dotnet restore DemoCICD.sln

      - name: Build Project
        run: dotnet build DemoCICD.sln --configuration Release --no-restore

      - name: Build Docker Image
        run: docker build -t democicd:latest ./DemoCICD
