
name: Demo CI/CD Pipeline

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore DemoCICD.sln

      - name: Build Project
        run: dotnet build DemoCICD.sln --configuration Release --no-restore

      - name: Publish Project
        run: dotnet publish DemoCICD/DemoCICD.csproj --configuration Release --output ./publish

      - name: Build Docker Image
        run: docker build -t democicd:latest ./DemoCICD
