 name: Demo CI

on:
  push:
    branches:
      - production

jobs:
  build:
    uses: mariamlabib106/pipeline-templates/.github/workflows/dotnet-build.yml@main
    with:
      dotnet-version: "8.0.x"
      build-configuration: "Release"
      project-name: "DemoCICD"
      environment: "Production"

    - name: Build Project
      run: dotnet build --configuration Release --no-restore
